# Generated by Django 5.0.6 on 2024-07-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPF',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('code', models.IntegerField()),
                ('s_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('s_create', models.DateTimeField()),
                ('s_status', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_uzl', models.CharField(max_length=255)),
                ('s_user_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('keys', models.CharField(max_length=255)),
            ],
        ),
    ]
