# Generated by Django 5.0.6 on 2024-07-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0005_alter_opf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='opf',
            name='parent_id',
            field=models.IntegerField(unique=True),
        ),
    ]
