# Generated by Django 5.0.6 on 2024-07-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0009_okonx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='okonx',
            old_name='ranch_code',
            new_name='branch_code',
        ),
    ]
