# Generated by Django 5.0.6 on 2024-07-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0013_alter_soogu_code_okpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soogu',
            name='s_create',
            field=models.DateTimeField(null=True),
        ),
    ]
