# Generated by Django 5.0.6 on 2024-07-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0019_alter_soogu_s_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soogu',
            name='s_create',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
