# Generated by Django 5.0.6 on 2024-07-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0022_alter_soogu_s_create'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Soogu',
        ),
    ]
