# Generated by Django 5.0.6 on 2024-07-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0028_alter_soogu_s_create_alter_soogu_s_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soogu',
            name='s_create',
            field=models.DateTimeField(),
        ),
    ]
