# Generated by Django 5.0.6 on 2024-07-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0034_doctype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DOCTYPE',
        ),
    ]
