# Generated by Django 5.0.6 on 2024-07-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soato',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('s_comment', models.TextField(blank=True, null=True)),
                ('s_create', models.DateTimeField()),
                ('s_status', models.CharField(max_length=10)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_uzl', models.CharField(max_length=255)),
                ('name_center_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('name_center_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('name_center_uzl', models.CharField(blank=True, max_length=255, null=True)),
                ('s_user_id', models.IntegerField()),
                ('parent_code', models.CharField(max_length=50)),
                ('keys', models.CharField(max_length=255)),
            ],
        ),
    ]
