# Generated by Django 5.0.6 on 2024-07-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0010_rename_ranch_code_okonx_branch_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soogu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('code_okpo', models.IntegerField()),
                ('s_comment', models.TextField(blank=True, null=True)),
                ('s_create', models.DateTimeField()),
                ('s_status', models.CharField(max_length=10)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_uzl', models.CharField(max_length=255)),
                ('s_user_id', models.IntegerField()),
                ('code', models.IntegerField()),
            ],
        ),
    ]
