# Generated by Django 5.0.6 on 2024-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0011_soogu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soogu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
