# Generated by Django 5.0.6 on 2024-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0014_alter_soogu_s_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soogu',
            name='code_okpo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='soogu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
