# Generated by Django 5.0.6 on 2024-07-29 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0015_alter_soogu_code_okpo_alter_soogu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soogu',
            name='s_create',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 10, 17, 25, 359185, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
