# Generated by Django 5.0.6 on 2024-07-29 10:27

import references_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0020_alter_soogu_s_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soogu',
            name='s_create',
            field=models.DateTimeField(),
        ),
    ]
