# Generated by Django 5.0.6 on 2024-07-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0024_soogu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Soogu',
        ),
    ]
