# Generated by Django 5.0.6 on 2024-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0025_delete_soogu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOOGU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('code_okpo', models.IntegerField()),
                ('s_comment', models.TextField(blank=True, null=True)),
                ('s_create', models.DateTimeField()),
                ('s_status', models.CharField(max_length=10)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_uzl', models.CharField(max_length=255)),
                ('s_user_id', models.IntegerField()),
                ('code', models.IntegerField()),
            ],
        ),
    ]
