# Generated by Django 5.0.6 on 2024-07-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0026_soogu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soogu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
