# Generated by Django 5.0.6 on 2024-07-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0027_alter_soogu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soogu',
            name='s_create',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='soogu',
            name='s_status',
            field=models.CharField(),
        ),
    ]
