# Generated by Django 5.0.6 on 2024-07-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0030_alter_soogu_id_alter_soogu_s_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soogu',
            name='s_create',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
