# Generated by Django 5.0.6 on 2024-07-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0031_alter_soogu_s_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soogu',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
