# Generated by Django 5.0.6 on 2024-07-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0032_alter_soogu_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('code', models.IntegerField()),
                ('s_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('s_create', models.DateTimeField()),
                ('s_status', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_uzl', models.CharField(max_length=255)),
                ('s_user_id', models.IntegerField()),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('keys', models.CharField(max_length=255)),
            ],
        ),
    ]
